Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  find: `dummy': No such file or directory
find: `dummy': No such file or directory
packages/apps/Settings/src/com/android/settings/ZonePicker.java:283: error: incompatible types
                final String localeName = Locale.getDefault();
                                                           ^
  required: String
  found:    Locale
packages/apps/Settings/src/com/android/settings/ZonePicker.java:284: error: cannot find symbol
                displayName = TimeZoneNames.getExemplarLocation(locale, tz);
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Label: Verified=-1